#!/usr/bin/env ansible-playbook
---
- hosts: 'all'
  roles:
  - 'common'
  - 'admin'

- hosts: 'docker'
  roles:
  - 'docker_ce'
  - 'age'

- hosts: 'glrunner'
  roles:
  - 'gitlab_runner'

- hosts: 'kube'
  roles:
  - 'kube'

- hosts: 'all'
  roles:
  - 'updates'
