#!/usr/bin/env ansible-playbook
---
- hosts: 'all'
  roles:
  - 'common'
  - 'admin'
  - 'ansible'

- hosts: 'docker'
  roles:
  - 'docker_ce_arm'
  - 'age'

- hosts: 'glrunner'
  roles:
  - 'gitlab_runner'

- hosts: 'k3s'
  roles:
  - 'k3s'

- hosts: 'all'
  roles:
  - 'updates'

- hosts: 'pi4'
  roles:
  - 'raspios'
