---

- name: 'manage devops group'
  become: true
  group:
    name: 'devops'
    state: 'present'

- name: 'manage ansible user'
  become: true
  user:
    name: 'devoops'
    password: '!'
    shell: '/bin/bash'
    create_home: 'yes'
    state: 'present'
    update_password: 'on_create'

- name: 'manage ansible user groups'
  become: true
  user:
    name: 'devoops'
    append: true
    groups:
    - 'sudo'
    - 'adm'
    - 'systemd-journal'
    - 'staff'
    - 'ssh-enabled'
    - 'devops'

- name: 'manage ansible user .ssh directory'
  file:
    state: 'directory'
    path: '/home/devoops/.ssh/'
    owner: 'devoops'
    group: 'devoops'
    mode: '0700'

- name: 'get latest ansible keys checksum' # noqa 301
  local_action:
    module: 'shell'
    cmd: >
      curl -s --head "https://gitlab.cr.imson.co/api/v4/projects/107/repository/files/ansible_keys?ref=master" \
        | grep x-gitlab-content-sha256 \
        | awk "{print \$2}"
    warn: false
  register: 'ansible_keys_checksum'

- name: 'get local ansible keys checksum'
  stat:
    path: '/home/devoops/.ssh/authorized_keys'
    checksum_algorithm: 'sha256'
  register: 'local_ansible_keys_checksum'
  changed_when: 'local_ansible_keys_checksum.stat.checksum != ansible_keys_checksum.stdout'

- name: 'update ansible keys'
  block:
  - name: 'create local temp file' # noqa 305
    local_action:
      module: 'shell'
      cmd: 'mktemp'
    register: 'ansible_temp'
  - name: 'download latest ansible keys'
    local_action:
      module: 'get_url'
      url: 'https://gitlab.cr.imson.co/cr.imson.co/ssh-keys/-/raw/master/ansible_keys'
      dest: '{{ ansible_temp.stdout }}'
  - name: 'upload latest ansible keys'
    copy:
      src: '{{ ansible_temp.stdout }}'
      dest: '/home/devoops/.ssh/authorized_keys'
      owner: 'devoops'
      group: 'devoops'
      mode: '0700'
  - name: 'delete temp file'
    local_action:
      module: 'file'
      path: '{{ ansible_temp.stdout }}'
      state: 'absent'
  when: 'local_ansible_keys_checksum.changed'

- name: 'manage sudoers'
  become: true
  copy:
    dest: '/etc/sudoers.d/01-ansible'
    content: |
      # Allow the group "ansible" to run sudo (ALL) with NOPASSWD
      %devops       ALL=(ALL)       NOPASSWD: ALL
    owner: 'root'
    group: 'root'
    mode: '0440'
