---
# common configuration playbook

- name: 'install common dependencies'
  become: true
  apt:
    install_recommends: 'no'
    name:
    - 'git'
    - 'htop'
    - 'zsh'
    - 'stow'
    state: 'present'
